// Code generated by https://github.com/go-dev-frame/sponge, DO NOT EDIT.

package v1

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	errcode "github.com/go-dev-frame/sponge/pkg/errcode"
	middleware "github.com/go-dev-frame/sponge/pkg/gin/middleware"
	zap "go.uber.org/zap"
)

// import packages: strings. context. errcode. middleware. zap. gin.

type UserExampleLogicer interface {
	Create(ctx context.Context, req *CreateUserExampleRequest) (*CreateUserExampleReply, error)
	DeleteByID(ctx context.Context, req *DeleteUserExampleByIDRequest) (*DeleteUserExampleByIDReply, error)
	UpdateByID(ctx context.Context, req *UpdateUserExampleByIDRequest) (*UpdateUserExampleByIDReply, error)
	GetByID(ctx context.Context, req *GetUserExampleByIDRequest) (*GetUserExampleByIDReply, error)
	List(ctx context.Context, req *ListUserExampleRequest) (*ListUserExampleReply, error)
}

type UserExampleOption func(*userExampleOptions)

type userExampleOptions struct {
	isFromRPC  bool
	responser  errcode.Responser
	zapLog     *zap.Logger
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *userExampleOptions) apply(opts ...UserExampleOption) { _ = "STUB: not implemented"; return }

func WithUserExampleHTTPResponse() UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func WithUserExampleRPCResponse() UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func WithUserExampleResponser(responser errcode.Responser) UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func WithUserExampleLogger(zapLog *zap.Logger) UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func WithUserExampleErrorToHTTPCode(e ...*errcode.Error) UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func WithUserExampleRPCStatusToHTTPCode(s ...*errcode.RPCStatus) UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func WithUserExampleWrapCtx(wrapCtxFn func(c *gin.Context) context.Context) UserExampleOption {
	_ = "STUB: not implemented"
	return *new(UserExampleOption)
}

func RegisterUserExampleRouter(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic UserExampleLogicer,
	opts ...UserExampleOption) {
	_ = "STUB: not implemented"
	return
}

type userExampleRouter struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                UserExampleLogicer
	iResponse             errcode.Responser
	zapLog                *zap.Logger
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *userExampleRouter) register() { _ = "STUB: not implemented"; return }

func (r *userExampleRouter) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	_ = "STUB: not implemented"
	return nil
}

// determine if a route group is hit or miss, left prefix rule

// determine if a single route has been hit

var _ middleware.CtxKeyString

func (r *userExampleRouter) Create_0(c *gin.Context) { _ = "STUB: not implemented"; return }

func (r *userExampleRouter) DeleteByID_0(c *gin.Context) { _ = "STUB: not implemented"; return }

func (r *userExampleRouter) UpdateByID_0(c *gin.Context) { _ = "STUB: not implemented"; return }

func (r *userExampleRouter) GetByID_0(c *gin.Context) { _ = "STUB: not implemented"; return }

func (r *userExampleRouter) List_0(c *gin.Context) { _ = "STUB: not implemented"; return }
