// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/serverNameExample/v1/userExample.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateUserExampleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserExampleRequest) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on CreateUserExampleRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserExampleRequestMultiError, or nil if none found.
func (m *CreateUserExampleRequest) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *CreateUserExampleRequest) validate(all bool) error { _ = "STUB: not implemented"; return nil }

func (m *CreateUserExampleRequest) _validateHostname(host string) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateUserExampleRequest) _validateEmail(addr string) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateUserExampleRequestMultiError is an error wrapping multiple validation
// errors returned by CreateUserExampleRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateUserExampleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserExampleRequestMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m CreateUserExampleRequestMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// CreateUserExampleRequestValidationError is the validation error returned by
	// CreateUserExampleRequest.Validate if the designated constraints aren't met.
	return nil
}

type CreateUserExampleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserExampleRequestValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e CreateUserExampleRequestValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e CreateUserExampleRequestValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e CreateUserExampleRequestValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e CreateUserExampleRequestValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e CreateUserExampleRequestValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = CreateUserExampleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserExampleRequestValidationError{}

var _CreateUserExampleRequest_Phone_Pattern = regexp.MustCompile("^1[3456789]\\d{9}$")

// Validate checks the field values on CreateUserExampleReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserExampleReply) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on CreateUserExampleReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserExampleReplyMultiError, or nil if none found.
func (m *CreateUserExampleReply) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *CreateUserExampleReply) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// no validation rules for Id

// CreateUserExampleReplyMultiError is an error wrapping multiple validation
// errors returned by CreateUserExampleReply.ValidateAll() if the designated
// constraints aren't met.
type CreateUserExampleReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserExampleReplyMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m CreateUserExampleReplyMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// CreateUserExampleReplyValidationError is the validation error returned by
	// CreateUserExampleReply.Validate if the designated constraints aren't met.
	return nil
}

type CreateUserExampleReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserExampleReplyValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e CreateUserExampleReplyValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e CreateUserExampleReplyValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e CreateUserExampleReplyValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e CreateUserExampleReplyValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e CreateUserExampleReplyValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = CreateUserExampleReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserExampleReplyValidationError{}

// Validate checks the field values on DeleteUserExampleByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserExampleByIDRequest) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on DeleteUserExampleByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserExampleByIDRequestMultiError, or nil if none found.
func (m *DeleteUserExampleByIDRequest) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *DeleteUserExampleByIDRequest) validate(all bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUserExampleByIDRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteUserExampleByIDRequest.ValidateAll() if
// the designated constraints aren't met.
type DeleteUserExampleByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserExampleByIDRequestMultiError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserExampleByIDRequestMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// DeleteUserExampleByIDRequestValidationError is the validation error returned
	// by DeleteUserExampleByIDRequest.Validate if the designated constraints
	// aren't met.
	return nil
}

type DeleteUserExampleByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserExampleByIDRequestValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e DeleteUserExampleByIDRequestValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e DeleteUserExampleByIDRequestValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e DeleteUserExampleByIDRequestValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e DeleteUserExampleByIDRequestValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e DeleteUserExampleByIDRequestValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = DeleteUserExampleByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserExampleByIDRequestValidationError{}

// Validate checks the field values on DeleteUserExampleByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserExampleByIDReply) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on DeleteUserExampleByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserExampleByIDReplyMultiError, or nil if none found.
func (m *DeleteUserExampleByIDReply) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *DeleteUserExampleByIDReply) validate(all bool) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUserExampleByIDReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteUserExampleByIDReply.ValidateAll() if
// the designated constraints aren't met.
type DeleteUserExampleByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserExampleByIDReplyMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m DeleteUserExampleByIDReplyMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// DeleteUserExampleByIDReplyValidationError is the validation error returned
	// by DeleteUserExampleByIDReply.Validate if the designated constraints aren't met.
	return nil
}

type DeleteUserExampleByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserExampleByIDReplyValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e DeleteUserExampleByIDReplyValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e DeleteUserExampleByIDReplyValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e DeleteUserExampleByIDReplyValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e DeleteUserExampleByIDReplyValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e DeleteUserExampleByIDReplyValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = DeleteUserExampleByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserExampleByIDReplyValidationError{}

// Validate checks the field values on UpdateUserExampleByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserExampleByIDRequest) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on UpdateUserExampleByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserExampleByIDRequestMultiError, or nil if none found.
func (m *UpdateUserExampleByIDRequest) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *UpdateUserExampleByIDRequest) validate(all bool) error {
	_ = "STUB: not implemented"
	return nil
}

// no validation rules for Name

// no validation rules for Email

// no validation rules for Password

// no validation rules for Phone

// no validation rules for Avatar

// no validation rules for Age

// no validation rules for Gender

// no validation rules for Status

// no validation rules for LoginAt

// UpdateUserExampleByIDRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateUserExampleByIDRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateUserExampleByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserExampleByIDRequestMultiError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserExampleByIDRequestMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// UpdateUserExampleByIDRequestValidationError is the validation error returned
	// by UpdateUserExampleByIDRequest.Validate if the designated constraints
	// aren't met.
	return nil
}

type UpdateUserExampleByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserExampleByIDRequestValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e UpdateUserExampleByIDRequestValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e UpdateUserExampleByIDRequestValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e UpdateUserExampleByIDRequestValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e UpdateUserExampleByIDRequestValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e UpdateUserExampleByIDRequestValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = UpdateUserExampleByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserExampleByIDRequestValidationError{}

// Validate checks the field values on UpdateUserExampleByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserExampleByIDReply) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on UpdateUserExampleByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserExampleByIDReplyMultiError, or nil if none found.
func (m *UpdateUserExampleByIDReply) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *UpdateUserExampleByIDReply) validate(all bool) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateUserExampleByIDReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateUserExampleByIDReply.ValidateAll() if
// the designated constraints aren't met.
type UpdateUserExampleByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserExampleByIDReplyMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m UpdateUserExampleByIDReplyMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// UpdateUserExampleByIDReplyValidationError is the validation error returned
	// by UpdateUserExampleByIDReply.Validate if the designated constraints aren't met.
	return nil
}

type UpdateUserExampleByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserExampleByIDReplyValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e UpdateUserExampleByIDReplyValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e UpdateUserExampleByIDReplyValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e UpdateUserExampleByIDReplyValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e UpdateUserExampleByIDReplyValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e UpdateUserExampleByIDReplyValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = UpdateUserExampleByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserExampleByIDReplyValidationError{}

// Validate checks the field values on UserExample with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserExample) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on UserExample with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserExampleMultiError, or
// nil if none found.
func (m *UserExample) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *UserExample) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// no validation rules for Id

// no validation rules for Name

// no validation rules for Email

// no validation rules for Phone

// no validation rules for Avatar

// no validation rules for Age

// no validation rules for Gender

// no validation rules for Status

// no validation rules for LoginAt

// no validation rules for CreatedAt

// no validation rules for UpdatedAt

// UserExampleMultiError is an error wrapping multiple validation errors
// returned by UserExample.ValidateAll() if the designated constraints aren't met.
type UserExampleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserExampleMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m UserExampleMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// UserExampleValidationError is the validation error returned by
	// UserExample.Validate if the designated constraints aren't met.
	return nil
}

type UserExampleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserExampleValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e UserExampleValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e UserExampleValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e UserExampleValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e UserExampleValidationError) ErrorName() string { _ = "STUB: not implemented"; return "" }

// Error satisfies the builtin error interface
func (e UserExampleValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = UserExampleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserExampleValidationError{}

// Validate checks the field values on GetUserExampleByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserExampleByIDRequest) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on GetUserExampleByIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserExampleByIDRequestMultiError, or nil if none found.
func (m *GetUserExampleByIDRequest) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *GetUserExampleByIDRequest) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// GetUserExampleByIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserExampleByIDRequest.ValidateAll() if the
// designated constraints aren't met.
type GetUserExampleByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserExampleByIDRequestMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m GetUserExampleByIDRequestMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// GetUserExampleByIDRequestValidationError is the validation error returned by
	// GetUserExampleByIDRequest.Validate if the designated constraints aren't met.
	return nil
}

type GetUserExampleByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserExampleByIDRequestValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e GetUserExampleByIDRequestValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e GetUserExampleByIDRequestValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e GetUserExampleByIDRequestValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e GetUserExampleByIDRequestValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e GetUserExampleByIDRequestValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = GetUserExampleByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserExampleByIDRequestValidationError{}

// Validate checks the field values on GetUserExampleByIDReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserExampleByIDReply) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on GetUserExampleByIDReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserExampleByIDReplyMultiError, or nil if none found.
func (m *GetUserExampleByIDReply) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *GetUserExampleByIDReply) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// GetUserExampleByIDReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserExampleByIDReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserExampleByIDReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserExampleByIDReplyMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m GetUserExampleByIDReplyMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// GetUserExampleByIDReplyValidationError is the validation error returned by
	// GetUserExampleByIDReply.Validate if the designated constraints aren't met.
	return nil
}

type GetUserExampleByIDReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserExampleByIDReplyValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e GetUserExampleByIDReplyValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e GetUserExampleByIDReplyValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e GetUserExampleByIDReplyValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e GetUserExampleByIDReplyValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e GetUserExampleByIDReplyValidationError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

var _ error = GetUserExampleByIDReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserExampleByIDReplyValidationError{}

// Validate checks the field values on ListUserExampleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserExampleRequest) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on ListUserExampleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUserExampleRequestMultiError, or nil if none found.
func (m *ListUserExampleRequest) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *ListUserExampleRequest) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// ListUserExampleRequestMultiError is an error wrapping multiple validation
// errors returned by ListUserExampleRequest.ValidateAll() if the designated
// constraints aren't met.
type ListUserExampleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserExampleRequestMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m ListUserExampleRequestMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// ListUserExampleRequestValidationError is the validation error returned by
	// ListUserExampleRequest.Validate if the designated constraints aren't met.
	return nil
}

type ListUserExampleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserExampleRequestValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e ListUserExampleRequestValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e ListUserExampleRequestValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e ListUserExampleRequestValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e ListUserExampleRequestValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e ListUserExampleRequestValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = ListUserExampleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserExampleRequestValidationError{}

// Validate checks the field values on ListUserExampleReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserExampleReply) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on ListUserExampleReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUserExampleReplyMultiError, or nil if none found.
func (m *ListUserExampleReply) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *ListUserExampleReply) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// no validation rules for Total

// ListUserExampleReplyMultiError is an error wrapping multiple validation
// errors returned by ListUserExampleReply.ValidateAll() if the designated
// constraints aren't met.
type ListUserExampleReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserExampleReplyMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m ListUserExampleReplyMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// ListUserExampleReplyValidationError is the validation error returned by
	// ListUserExampleReply.Validate if the designated constraints aren't met.
	return nil
}

type ListUserExampleReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserExampleReplyValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e ListUserExampleReplyValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e ListUserExampleReplyValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e ListUserExampleReplyValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e ListUserExampleReplyValidationError) ErrorName() string {
	_ = "STUB: not implemented"
	return ""
}

// Error satisfies the builtin error interface
func (e ListUserExampleReplyValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = ListUserExampleReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserExampleReplyValidationError{}
