// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/types/types.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Params with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Params) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on Params with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ParamsMultiError, or nil if none found.
func (m *Params) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *Params) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// no validation rules for Page

// no validation rules for Limit

// no validation rules for Sort

// ParamsMultiError is an error wrapping multiple validation errors returned by
// Params.ValidateAll() if the designated constraints aren't met.
type ParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParamsMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m ParamsMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// ParamsValidationError is the validation error returned by Params.Validate if
	// the designated constraints aren't met.
	return nil
}

type ParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParamsValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e ParamsValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e ParamsValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e ParamsValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e ParamsValidationError) ErrorName() string { _ = "STUB: not implemented"; return "" }

// Error satisfies the builtin error interface
func (e ParamsValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = ParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParamsValidationError{}

// Validate checks the field values on Column with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Column) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on Column with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ColumnMultiError, or nil if none found.
func (m *Column) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *Column) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// no validation rules for Name

// no validation rules for Exp

// no validation rules for Value

// no validation rules for Logic

// ColumnMultiError is an error wrapping multiple validation errors returned by
// Column.ValidateAll() if the designated constraints aren't met.
type ColumnMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ColumnMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m ColumnMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// ColumnValidationError is the validation error returned by Column.Validate if
	// the designated constraints aren't met.
	return nil
}

type ColumnValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ColumnValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e ColumnValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e ColumnValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e ColumnValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e ColumnValidationError) ErrorName() string { _ = "STUB: not implemented"; return "" }

// Error satisfies the builtin error interface
func (e ColumnValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = ColumnValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ColumnValidationError{}

// Validate checks the field values on Conditions with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Conditions) Validate() error { _ = "STUB: not implemented"; return nil }

// ValidateAll checks the field values on Conditions with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConditionsMultiError, or
// nil if none found.
func (m *Conditions) ValidateAll() error { _ = "STUB: not implemented"; return nil }

func (m *Conditions) validate(all bool) error { _ = "STUB: not implemented"; return nil }

// ConditionsMultiError is an error wrapping multiple validation errors
// returned by Conditions.ValidateAll() if the designated constraints aren't met.
type ConditionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConditionsMultiError) Error() string { _ = "STUB: not implemented"; return "" }

// AllErrors returns a list of validation violation errors.
func (m ConditionsMultiError) AllErrors() []error {
	_ = "STUB: not implemented"

	// ConditionsValidationError is the validation error returned by
	// Conditions.Validate if the designated constraints aren't met.
	return nil
}

type ConditionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConditionsValidationError) Field() string {
	_ = "STUB: not implemented"

	// Reason function returns reason value.
	return ""
}

func (e ConditionsValidationError) Reason() string {
	_ = "STUB: not implemented"

	// Cause function returns cause value.
	return ""
}

func (e ConditionsValidationError) Cause() error {
	_ = "STUB: not implemented"

	// Key function returns key value.
	return nil
}

func (e ConditionsValidationError) Key() bool {
	_ = "STUB: not implemented"

	// ErrorName returns error name.
	return false
}

func (e ConditionsValidationError) ErrorName() string { _ = "STUB: not implemented"; return "" }

// Error satisfies the builtin error interface
func (e ConditionsValidationError) Error() string { _ = "STUB: not implemented"; return "" }

var _ error = ConditionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConditionsValidationError{}
