// Code generated by https://github.com/go-dev-frame/sponge; DO NOT EDIT.

package config

func NewCenter(configFile string) (*Center, error) { _ = "STUB: not implemented"; return nil, nil }

type Center struct {
	Nacos Nacos `yaml:"nacos" json:"nacos"`
}

type Nacos struct {
	ContextPath string `yaml:"contextPath" json:"contextPath"`
	DataID      string `yaml:"dataID" json:"dataID"`
	Format      string `yaml:"format" json:"format"`
	Group       string `yaml:"group" json:"group"`
	IPAddr      string `yaml:"ipAddr" json:"ipAddr"`
	NamespaceID string `yaml:"namespaceID" json:"namespaceID"`
	Port        int    `yaml:"port" json:"port"`
	Scheme      string `yaml:"scheme" json:"scheme"`
}
